channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - dill==0.3.9
  - numpy==1.23.5
  - pandas==2.2.3
  - torch==1.12.0
  - tqdm==4.66.5
name: mlflow-env
